name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: build
        run: |
          yarn install
          yarn build
          echo '출력 테스트 시작'
          echo ${{ secrets.GIST_ID }}
          echo ${{ secrets.GH_TOKEN }}
          echo '출력 테스트 끝'
      - name: commit change & push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull
          git add .
          git commit --allow-empty -m ":robot: build automatically"
          git push
      - name: repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: devyeony/productive-box
          event-type: build-event
